server:
  port: 8101

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5400/stream-service
    username: admin
    password: 123450000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
#      search:
#        default:
#          directory_provider: filesystem
#          indexBase: "/lucene/indexes"
  flyway:
    schemas: public
    enabled: true
  threads:
    virtual:
      enabled: true